const workExperienceData = [
	{
		companyName: "University of Nevada, Las Vegas",
		yearsWorked: "June 2025 - Current",
		jobTitle: "Student System Administrator/Engineering, Level 1",
		jobDescription: [
			"• Build, deploy, and administer systems; perform OS upgrades, patching, and performance tuning while providing technical support and documenting infrastructure.",
			"• Leverage cloud platforms (AWS, Azure) and infrastructure automation tools (GitLab, Ansible, Terraform, Packer) to manage system lifecycles and disaster recovery.",
			"• Responsibilities include providing technical support to students and faculty, managing system updates, and ensuring the security of departmental IT resources.",
		],
		techStack: [
			"Python",
			"VSCode",
			"GitLab",
			"Ansible",
			"Terraform",
			"Packer",
			"AWS",
			"Azure",
		],
	},
	{
		companyName: "Batchl",
		yearsWorked: "May 2025 - Current",
		jobTitle: "Project Engineer - MVP Development Intern",
		jobDescription: [
			"• Developing a mobile-first Minimum Viable Product (MVP) by translating Figma designs into a functional application using React Native and Python.",
			"• Collaborating directly with the founder to define product vision, contribute to the development roadmap, and implement features in a lean, experimental environment.",
			"• Responsibilities include building the front-end application, integrating with backend services, and ensuring a seamless user experience.",
		],
		techStack: [
			"Python",
			"VSCode",
			"React Native",
			"Figma",
			"JS/TS",
			"Git/GitHub",
			"GitHub",
			"Mobile Development",
			"UI/UX Design",
		],
	},
	{
		companyName: "University of Nevada, Las Vegas",
		yearsWorked: "Jan 2025 - Current",
		jobTitle: "Computer Science Graduate Assistant",
		jobDescription: [
			"• Worked approximately 20 hours per week while attending school full-time",
			"• Selected for a competitive assistantship to support the Computer Science department's academic mission. Currently assisting in teaching and grading for the 'Introduction to Python for Data Science' course.",
			"• Responsibilities include grading assignments and quizzes, assisting students with understanding programming concepts, and supporting the professor in teaching object-oriented programming and data science topics.",
		],
		techStack: [
			"Python",
			"VSCode",
			"Jupyter Notebook",
			"Data Science",
			"NumPy",
			"Pandas",
		],
	},
	{
		companyName: "Mission Support and Test Services",
		yearsWorked: "August 2023 - May 2024",
		jobTitle: "Casual Employee",
		jobDescription: [
			"• Worked approximately 20 hours per week while attending school full-time",
			"• Modernized internal websites using Angular and TypeScript, integrating automated data validation and customizable interfaces, improving data accuracy by 30% and reducing user input errors by 20%.",
			"• Collaborated with scientists and engineers throughout design, development, and testing phases, incorporating feedback to introduce new features, significantly boosting platform responsiveness and increasing user engagement by 20%.",
		],
		techStack: [
			"Angular",
			"TypeScript",
			"HTML",
			"CSS",
			"JavaScript",
			"Azure DevOps",
			"Agile",
		],
	},
	{
		companyName: "Mission Support and Test Services",
		yearsWorked: "May 2023 - August 2023",
		jobTitle: "Science & Engineering Summer Intern",
		jobDescription: [
			"• Worked full time / 40 hours per week",
			"• Designed a field sample simulation tool, reducing data entry time by 40% and auto-calculating values to streamline training exercises for Nuclear Emergency Responders during Federal Radiological Monitoring and Assessment Center (FRMAC) training events.",
			"• Enhanced simulation capabilities to support Nuclear Emergency Response training across the NNSA complex with new designs and features using Angular and TypeScript.",
		],
		techStack: [
			"Angular",
			"TypeScript",
			"HTML",
			"CSS",
			"JavaScript",
			"Azure DevOps",
			"Agile",
		],
	},
	{
		companyName: "University of Nevada, Las Vegas",
		yearsWorked: "January 2022 - May 2023",
		jobTitle: "Computer Science I Teaching Assistant",
		jobDescription: [
			"• Worked approximately 10 hours per week while attending school full-time",
			"• Guided during office hours to support over 30 students weekly in mastering C++ concepts and completing assignments, leading to an average grade improvement of one letter.",
			"• Graded assignments and delivered constructive feedback, maintaining a grading turnaround time of less than 48 hours.",
		],
		techStack: ["C++", "Visual Studio Code", "Visual Studio", "gdb", "lldb"],
	},
	{
		companyName: "University of Nevada, Las Vegas",
		yearsWorked: "August 2023 - December 2023",
		jobTitle: "Undergraduate Research Assistant",
		jobDescription: [
			"• Use Python-based machine learning techniques to process simulation snapshots and compare against different simulation methods",
			"• Analyze simulated astronomy data, which required reading large datasets, performing mathematical analysis of them, and generating visualizations",
		],
		techStack: [
			"Python",
			"Jupyter Notebook",
			"NumPy",
			"Matplotlib",
			"Pandas",
			"Scikit-learn",
			"Machine Learning",
		],
	},
	{
		companyName: "IBM",
		yearsWorked: "June 2022 – August 2022",
		jobTitle: "2022 Accelerate Program: Software Track",
		jobDescription: [
			"• Built a front-end application in React utilizing backend services by using Express, Node.js, and front-end languages",
			"• Grow programming skills while enhancing core competencies and understanding of coding platforms",
			"• Expand ability to work in agile teams, think critically, problem solve, and sharpen logic skills",
		],
		techStack: [
			"React",
			"Express",
			"Node.js",
			"HTML",
			"CSS",
			"JavaScript",
			"Agile",
		],
	},
	{
		companyName: "AT&T",
		yearsWorked: "June 2021 – July 2021",
		jobTitle: "AT&T Summer Learning Academy Extern",
		jobDescription: [
			"• Acquired business and technical acumen in Cybersecurity, Machine Learning, and Design Thinking along with personal growth and professional development across 80 hours of online learning",
			"• Gained insights and advice on business, leadership, technology and career from more than 50 business executives and recognized experts",
			"• Completed beyond 30 different entry-level training in communication and leadership, finance, media and technology",
			"• Networked with students and AT&T employees and asked questions of nationally renowned speakers",
		],
		techStack: [
			"Cybersecurity",
			"Machine Learning",
			"Design Thinking",
			"Leadership",
			"Communication",
		],
	},
];

export { workExperienceData };
